# Generated by Django 3.2.25 on 2026-02-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('unit_one_current', models.FloatField(default=0, null=True)),
                ('unit_one_previous', models.FloatField(default=0, null=True)),
                ('unit_two_current', models.FloatField(default=0, null=True)),
                ('unit_two_previous', models.FloatField(default=0, null=True)),
                ('unit_three_current', models.FloatField(default=0, null=True)),
                ('unit_three_previous', models.FloatField(default=0, null=True)),
                ('unit_four_current', models.FloatField(default=0, null=True)),
                ('unit_four_previous', models.FloatField(default=0, null=True)),
                ('unit_five_current', models.FloatField(default=0, null=True)),
                ('unit_five_previous', models.FloatField(default=0, null=True)),
                ('unit_six_current', models.FloatField(default=0, null=True)),
                ('unit_six_previous', models.FloatField(default=0, null=True)),
                ('unit_one_equal', models.FloatField(default=0, null=True)),
                ('unit_two_equal', models.FloatField(default=0, null=True)),
                ('unit_three_equal', models.FloatField(default=0, null=True)),
                ('unit_four_equal', models.FloatField(default=0, null=True)),
                ('unit_five_equal', models.FloatField(default=0, null=True)),
                ('unit_six_equal', models.FloatField(default=0, null=True)),
                ('total_diesel', models.FloatField(default=0, null=True)),
                ('diesel_rate', models.FloatField(default=119.1, null=True)),
                ('diesel_Rs', models.FloatField(default=0, null=True)),
                ('total_petrol', models.FloatField(default=0, null=True)),
                ('petrol_rate', models.FloatField(default=122.4, null=True)),
                ('petrol_Rs', models.FloatField(default=0, null=True)),
                ('test_diesel', models.FloatField(default=0, null=True)),
                ('testDie_rate', models.FloatField(default=119.1, null=True)),
                ('testDie_Rs', models.FloatField(default=0, null=True)),
                ('test_petrol', models.FloatField(default=0, null=True)),
                ('testPet_rate', models.FloatField(default=122.4, null=True)),
                ('testPet_Rs', models.FloatField(default=0, null=True)),
                ('credit_diesel', models.FloatField(default=0, null=True)),
                ('crdie_rate', models.FloatField(default=119.1, null=True)),
                ('crdie_Rs', models.FloatField(default=0, null=True)),
                ('credit_petrol', models.FloatField(default=0, null=True)),
                ('crPet_rate', models.FloatField(default=122.4, null=True)),
                ('crPet_Rs', models.FloatField(default=0, null=True)),
                ('cash_diesel', models.FloatField(default=0, null=True)),
                ('cashDie_rate', models.FloatField(default=119.1, null=True)),
                ('cashDie_Rs', models.FloatField(default=0, null=True)),
                ('cash_petrol', models.FloatField(default=0, null=True)),
                ('cashPet_rate', models.FloatField(default=122.4, null=True)),
                ('cashPet_Rs', models.FloatField(default=0, null=True)),
                ('dunit_one_current', models.FloatField(default=0, null=True)),
                ('dunit_one_previous', models.FloatField(default=0, null=True)),
                ('dunit_two_current', models.FloatField(default=0, null=True)),
                ('dunit_two_previous', models.FloatField(default=0, null=True)),
                ('dunit_three_current', models.FloatField(default=0, null=True)),
                ('dunit_three_previous', models.FloatField(default=0, null=True)),
                ('dunit_four_current', models.FloatField(default=0, null=True)),
                ('dunit_four_previous', models.FloatField(default=0, null=True)),
                ('dunit_five_current', models.FloatField(default=0, null=True)),
                ('dunit_five_previous', models.FloatField(default=0, null=True)),
                ('dunit_six_current', models.FloatField(default=0, null=True)),
                ('dunit_six_previous', models.FloatField(default=0, null=True)),
                ('dunit_one_equal', models.FloatField(default=0, null=True)),
                ('dunit_two_equal', models.FloatField(default=0, null=True)),
                ('dunit_three_equal', models.FloatField(default=0, null=True)),
                ('dunit_four_equal', models.FloatField(default=0, null=True)),
                ('dunit_five_equal', models.FloatField(default=0, null=True)),
                ('dunit_six_equal', models.FloatField(default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meterreading_meterreading_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meterreading_meterreading_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meterreading_meterreading_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['uid'], name='meterreadin_uid_2a1ce5_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['is_active'], name='meterreadin_is_acti_bdbd11_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['is_deleted'], name='meterreadin_is_dele_529dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['created_at'], name='meterreadin_created_ff3fb2_idx'),
        ),
    ]
