# Generated by Django 3.2.25 on 2026-02-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('exp_type', models.CharField(choices=[('CASH', 'CASH'), ('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('note', models.CharField(blank=True, max_length=300, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_expensedetail_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_expensedetail_deleted', to=settings.AUTH_USER_MODEL)),
                ('exp_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.expense')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_expensedetail_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='expensedetail',
            index=models.Index(fields=['uid'], name='expenses_ex_uid_2d1c6a_idx'),
        ),
        migrations.AddIndex(
            model_name='expensedetail',
            index=models.Index(fields=['is_active'], name='expenses_ex_is_acti_69bad9_idx'),
        ),
        migrations.AddIndex(
            model_name='expensedetail',
            index=models.Index(fields=['is_deleted'], name='expenses_ex_is_dele_f006b5_idx'),
        ),
        migrations.AddIndex(
            model_name='expensedetail',
            index=models.Index(fields=['created_at'], name='expenses_ex_created_218eca_idx'),
        ),
    ]
