# Generated by Django 3.2.25 on 2026-02-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_No', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('receive_date', models.DateTimeField(null=True)),
                ('quantity', models.FloatField(default=0, null=True)),
                ('rate', models.FloatField(default=0, null=True)),
                ('total', models.FloatField(default=0, null=True)),
                ('paid', models.FloatField(default=0, null=True)),
                ('remaining', models.FloatField(default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_purchase_created', to=settings.AUTH_USER_MODEL)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.dealer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_purchase_deleted', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_purchase_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['uid'], name='purchase_pu_uid_d1eb08_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['is_active'], name='purchase_pu_is_acti_c3a4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['is_deleted'], name='purchase_pu_is_dele_de3dbc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['created_at'], name='purchase_pu_created_aba566_idx'),
        ),
    ]
