# Generated by Django 3.2.25 on 2026-02-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateTimeField(null=True)),
                ('dip_one_hsd', models.FloatField(default=0, null=True)),
                ('ltrs_one_hsd', models.FloatField(default=0, null=True)),
                ('diff_ltrs_one_hsd', models.FloatField(default=0, null=True)),
                ('status_one_hsd', models.FloatField(default=0, null=True)),
                ('stock_one_hsd', models.FloatField(default=0, null=True)),
                ('sale_one_hsd', models.FloatField(default=0, null=True)),
                ('rmg_one_hsd', models.FloatField(default=0, null=True)),
                ('dip_two_hsd', models.FloatField(default=0, null=True)),
                ('ltrs_two_hsd', models.FloatField(default=0, null=True)),
                ('diff_ltrs_two_hsd', models.FloatField(default=0, null=True)),
                ('status_two_hsd', models.FloatField(default=0, null=True)),
                ('stock_two_hsd', models.FloatField(default=0, null=True)),
                ('sale_two_hsd', models.FloatField(default=0, null=True)),
                ('rmg_two_hsd', models.FloatField(default=0, null=True)),
                ('dip_pmg', models.FloatField(default=0, null=True)),
                ('ltrs_pmg', models.FloatField(default=0, null=True)),
                ('diff_pmg', models.FloatField(default=0, null=True)),
                ('status_pmg', models.FloatField(default=0, null=True)),
                ('stock_pmg', models.FloatField(default=0, null=True)),
                ('sale_pmg', models.FloatField(default=0, null=True)),
                ('rmg_pmg', models.FloatField(default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockregister_dailystock_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockregister_dailystock_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stockregister_dailystock_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='dailystock',
            index=models.Index(fields=['uid'], name='stockregist_uid_58da26_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystock',
            index=models.Index(fields=['is_active'], name='stockregist_is_acti_27aa15_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystock',
            index=models.Index(fields=['is_deleted'], name='stockregist_is_dele_d31c6c_idx'),
        ),
        migrations.AddIndex(
            model_name='dailystock',
            index=models.Index(fields=['created_at'], name='stockregist_created_297d44_idx'),
        ),
    ]
