# Generated by Django 3.2.25 on 2026-02-08 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TyreSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('invoiceType', models.CharField(choices=[('CASH', 'CASH'), ('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10, null=True)),
                ('catagery', models.CharField(choices=[('Nil', 'Nil'), ('Bill Paid', 'Bill Paid')], max_length=10, null=True)),
                ('invoiceNo', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.FloatField(default=0, null=True)),
                ('saleprice', models.FloatField(default=0, null=True)),
                ('purchase', models.FloatField(default=0, null=True)),
                ('totalAmount', models.FloatField(default=0, null=True)),
                ('paidAmount', models.FloatField(default=0, null=True)),
                ('remainingAmount', models.FloatField(default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=20, null=True)),
                ('profit', models.FloatField(default=0, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.commission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_tyresale_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_tyresale_deleted', to=settings.AUTH_USER_MODEL)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_tyresale_updated', to=settings.AUTH_USER_MODEL)),
                ('vechile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.vechile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(null=True)),
                ('invoiceType', models.CharField(choices=[('CASH', 'CASH'), ('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=10, null=True)),
                ('catagery', models.CharField(choices=[('Nil', 'Nil'), ('Bill Paid', 'Bill Paid')], default='Nil', max_length=10, null=True)),
                ('invoiceNo', models.CharField(default='nil', max_length=20, null=True)),
                ('name', models.CharField(default='nil', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('quantity', models.FloatField(default=0, null=True)),
                ('saleprice', models.FloatField(default=273, null=True)),
                ('purchase', models.FloatField(default=266.09, null=True)),
                ('totalAmount', models.FloatField(default=0, null=True)),
                ('paidAmount', models.FloatField(default=0, null=True)),
                ('remainingAmount', models.FloatField(default=0, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.FloatField(default=0, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.commission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_sale_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_sale_deleted', to=settings.AUTH_USER_MODEL)),
                ('item_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_sale_updated', to=settings.AUTH_USER_MODEL)),
                ('vechile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.vechile')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='tyresale',
            index=models.Index(fields=['uid'], name='sale_tyresa_uid_9fb0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='tyresale',
            index=models.Index(fields=['is_active'], name='sale_tyresa_is_acti_918286_idx'),
        ),
        migrations.AddIndex(
            model_name='tyresale',
            index=models.Index(fields=['is_deleted'], name='sale_tyresa_is_dele_4a402e_idx'),
        ),
        migrations.AddIndex(
            model_name='tyresale',
            index=models.Index(fields=['created_at'], name='sale_tyresa_created_81e7e8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['uid'], name='sale_sale_uid_c39ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_active'], name='sale_sale_is_acti_dd8b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_deleted'], name='sale_sale_is_dele_7c916c_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='sale_sale_created_51b911_idx'),
        ),
    ]
